### ISSUE TITLE
合约 table 重构。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-EOS-contract#9]
<img width="632" alt="屏幕快照 2019-03-18 下午3 35 05" src="https://user-images.githubusercontent.com/2507027/54513804-6f6dd580-4993-11e9-86ab-1a396b82dbc7.png">

为了做完 MVP，需要完成 [打赏与分享功能](https://github.com/smart-signature/smart-signature-future/issues/24)，according to Joe 的提议（参见上图），我会开始重构合约的 Table。

目前采用账户合约做 scope，并且直接删除 goods、order 等 table 的问题（暂时 hold）。
（似乎 sign table 也可以用合约账户做 scope，但为了减少工作量，本次不进行修改。）

**Comment by lychees** [comment]
@yukiexe 
Please review my last few commits.
Remember to clean all tables before deploy this new version (beta-version).

Thanks.

**Comment by yukiexe** [comment]
LGTM
& all done.
